#
# Software Name : towards5gs-helm
# SPDX-FileCopyrightText: Copyright (c) 2021 Orange
# SPDX-License-Identifier: Apache-2.0
#
# This software is distributed under the Apache License 2.0,
# the text of which is available at todo
# or see the "LICENSE" file for more details.
#
# Author: Abderaouf KHICHANE, Ilhem FAJJARI, Ayoub BOUSSELMI
# Software description: An open-source project providing Helm charts to deploy 5G components (Core + RAN) on top of Kubernetes
#
# Default values for networks5g chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  n2network:
    enabled: true
    name: n2network
    masterIf: eth0
    subnetIP: 10.100.50.248
    cidr: 29
    gatewayIP: 10.100.50.254
    excludeIP: 10.100.50.254
  
  n4network:
    enabled: true
    name: n4network
    masterIf: eth0
    subnetIP: 10.100.50.240
    cidr: 29
    gatewayIP: 10.100.50.246
    excludeIP: 10.100.50.246
    #prefixIP: 10.100.50
    #gateway: 1
  
  n3network:
    enabled: true
    name: n3network
    masterIf: eth0
    subnetIP: 10.100.50.232
    cidr: 29
    gatewayIP: 10.100.50.238
    excludeIP: 10.100.50.238
    #prefixIP: 10.100.50
    #gateway: 1
  
  n6network:
    enabled: true
    name: n6network
    masterIf: eth1
    subnetIP: 10.100.100.0
    cidr: 24
    gatewayIP: 10.100.100.1
    excludeIP: 10.100.100.254
    #prefixIP: 192.168.121     # The prefix IP of the Data Network
    #gateway: 1  # you should be able to access the Data Network through this gateway "192.168.121.1"
  
  n9network:
    enabled: true
    name: n9network
    masterIf: eth0
    subnetIP: 10.100.50.224
    cidr: 29
    gatewayIP: 10.100.50.230
    excludeIP: 10.100.50.230
  
  ovn4nfv:
    enabled: false
    name: ovn4nfv-k8s-plugin
    n6network:
      name: n6net
    n3network:
      name: n3net
    n9network:
      name: n9net
  
  



