#
# Software Name : towards5gs-helm
# SPDX-FileCopyrightText: Copyright (c) 2021 Orange
# SPDX-License-Identifier: Apache-2.0
#
# This software is distributed under the Apache License 2.0,
# the text of which is available at todo
# or see the "LICENSE" file for more details.
#
# Author: Abderaouf KHICHANE, Ilhem FAJJARI, Ayoub BOUSSELMI
# Software description: An open-source project providing Helm charts to deploy 5G components (Core + RAN) on top of Kubernetes
#
{{- if .Values.n3iwf.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.n3iwf.configmap.name }}
  labels:
    app: {{ .Values.global.projectName }}
data:
  n3iwfcfg.yaml: |
    info:
      version: 1.0.0
      description: N3IWF initial local configuration
    
    configuration:
      N3IWFInformation:
        GlobalN3IWFID:
          PLMNID:
            MCC: 208
            MNC: 93
          N3IWFID: 135
        Name:
          free5GC_N3IWF
        SupportedTAList:
          - TAC: 000001
            BroadcastPLMNList:
              - PLMNID:
                  MCC: 208
                  MNC: 93
                TAISliceSupportList:
                  - SNSSAI:
                      SST: 1
                      SD: 010203
                  - SNSSAI:
                      SST: 1
                      SD: 112233
      AMFSCTPAddresses:
        - IP:
{{- if and .Values.global.amf.service.ngap.enabled }}
          - {{ .Values.global.amf.service.ngap.name }}
{{- else }}
          - {{ .Values.global.amf.n2if.ipAddress }}
{{- end }}
      # Bind Interfaces
      # IKE interface
      IKEBindAddress: {{ .Values.n3iwf.ike.prefixIP }}.{{ .Values.n3iwf.ike.suffixIP }}  # contrarly to the example used in docker compose here we attribute a special interface for the IKE daemon (as specified in the free5gc main project in github)
      # IPSec virtual interface
      IPSecInterfaceAddress: {{ .Values.global.non3gppuesubnet.prefixIP }}.1
      # IPSec virtual interface mark
      IPSecInterfaceMark: 5
      # GTP interface
      GTPBindAddress: {{ .Values.n3iwf.n3if.ipAddress }}
    
      # NAS TCP Listen Port
      NASTCPPort: 20000
    
      # N3IWF FQDN
      FQDN: n3iwf.free5gc.org
    
      # Security
      # Private Key File Path
      PrivateKey:
      # Certificate Authority (CA)
      CertificateAuthority:
      # Certificate
      Certificate:
    
      # IP address that will be allocated to UE in IPSec tunnel
      UEIPAddressRange: {{ .Values.global.non3gppuesubnet.prefixIP }}.0/24
  n3iwf-ipsec.sh: |
    #!/bin/sh
    
    ### N3iwf IPSec tunnel configuration
    
    ip l add name ipsec0 type vti local {{ .Values.n3iwf.ike.prefixIP }}.{{ .Values.n3iwf.ike.suffixIP }} remote 0.0.0.0 key 5
    ip a add {{ .Values.global.non3gppuesubnet.prefixIP }}.1/24 dev ipsec0
    ip l set dev ipsec0 up
{{- end }}
