#
# Software Name : towards5gs-helm
# SPDX-FileCopyrightText: Copyright (c) 2021 Orange
# SPDX-License-Identifier: Apache-2.0
#
# This software is distributed under the Apache License 2.0,
# the text of which is available at todo
# or see the "LICENSE" file for more details.
#
# Author: Abderaouf KHICHANE, Ilhem FAJJARI, Ayoub BOUSSELMI
# Software description: An open-source project providing Helm charts to deploy 5G components (Core + RAN) on top of Kubernetes
#
{{- if and .Values.amf.enabled (.Values.global.amf.service.ngap.enabled) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.amf.service.ngap.name }}
  labels:
    project: {{ .Values.global.projectName }}
    nf: {{ .Values.amf.name }}
spec:
  type: {{ .Values.global.amf.service.ngap.type }}
  ports:
    - name: n2
      port: {{ .Values.global.amf.service.ngap.port }}
      nodePort: {{ .Values.global.amf.service.ngap.nodeport }}
      protocol: {{ .Values.global.amf.service.ngap.protocol }}
  selector:
    project: {{ .Values.global.projectName }}
    nf: {{ .Values.amf.name }}
{{- end }}

