#
# Software Name : towards5gs-helm
# SPDX-FileCopyrightText: Copyright (c) 2021 Orange
# SPDX-License-Identifier: Apache-2.0
#
# This software is distributed under the Apache License 2.0,
# the text of which is available at todo
# or see the "LICENSE" file for more details.
#
# Author: Abderaouf KHICHANE, Ilhem FAJJARI, Ayoub BOUSSELMI
# Software description: An open-source project providing Helm charts to deploy 5G components (Core + RAN) on top of Kubernetes
#
# Default values for free5gcUserPlane chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


global:
  projectName: free5gc
  userPlaneArchitecture: single  # possible values are "single" and "ulcl"
  multiCluster: false
  cpClusterIP: 192.168.121.16
  uesubnet: 10.1.0.0/17
  uesubnet1: 10.1.0.0/17
  uesubnet2: 10.1.128.0/17
  datanetworks:
    dn1: internet
    dn2: internet2
  image:
    registry: towards5gs
  upf:
    n4if:  # PFCP
      ipAddress: 10.100.50.241
    n3if:  # GTPU
      ipAddress: 10.100.50.233
    n6if:  # DN
      ipAddress: 10.100.100.12
    service:
      pfcp:
        enabled: false
        name: upf-n4
        port: 8805
        nodeport: 30805
        protocol: UDP
        type: NodePort
  upfb:
    n4if:  # PFCP
      ipAddress: 10.100.50.241
    n3if:  # GTPU
      ipAddress: 10.100.50.233
    n9if:  # GTPU
      ipAddress: 10.100.50.225
    n6if:  # DN
      ipAddress: 10.100.100.12
    service:
      pfcp:
        name: upfb-n4
        nodeport: 30805
  upf1:
    n4if:  # PFCP
      ipAddress: 10.100.50.242
    n9if:  # GTPU
      ipAddress: 10.100.50.226
    n6if:  # DN
      ipAddress: 10.100.100.13
    service:
      pfcp:
        name: upf1-n4
        nodeport: 30806
  upf2:
    n4if:  # PFCP
      ipAddress: 10.100.50.243
    n9if:  # GTPU
      ipAddress: 10.100.50.227
    n6if:  # DN
      ipAddress: 10.100.100.14
    service:
      pfcp:
        name: upf2-n4
        nodeport: 30807
#Global network parametes
  n4network:
    name: n4network
    subnetIP: 10.100.50.240
  n3network:
    name: n3network
    subnetIP: 10.100.50.232
  n6network:
    name: n6network
    subnetIP: 10.100.100.0     # The subnet IP of the Data Network
    gateway: 1
  n2network:
    enabled: false
  ovn4nfv:       # The ovn4nfv plugin can be used for N3 and N6 interfaces
    enabled: false
    name: ovn4nfv-k8s-plugin
    n6network:
      name: n6net
    n3network:
      name: n3net


upf:
  name: upf
  replicaCount: 1
  image:
    registry: niloysh
    name: free5gc-upf
    tag: "v3.0.5-testing-v1.1"
  configmap:
    name: upf-configmap
  volume:
    name: upf-volume
    mount: /free5gc/config/
# The followed values will be considered in the case of choosing "anchors" architecture for the user plane
upf1:
  name: upf1
  replicaCount: 1
  configmap:
    name: upf1-configmap
  volume:
    name: upf1-volume

upf2:
  name: upf2
  replicaCount: 1
  configmap:
    name: upf2-configmap
  volume:
    name: upf2-volume

upfb:
  name: upfb
  replicaCount: 1
  configmap:
    name: upfb-configmap
  volume:
    name: upfb-volume

createNetworks: true

