#
# Software Name : towards5gs-helm
# SPDX-FileCopyrightText: Copyright (c) 2021 Orange
# SPDX-License-Identifier: Apache-2.0
#
# This software is distributed under the Apache License 2.0,
# the text of which is available at todo
# or see the "LICENSE" file for more details.
#
# Author: Abderaouf KHICHANE, Ilhem FAJJARI, Ayoub BOUSSELMI
# Software description: An open-source project providing Helm charts to deploy 5G components (Core + RAN) on top of Kubernetes
#
{{- if .Values.udm.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Values.udm.name }}
  labels:
    project: {{ .Values.global.projectName }}
    nf: {{ .Values.udm.name }}
spec:
  selector:
    matchLabels:
      project: {{ .Values.global.projectName }}
      nf: {{ .Values.udm.name }}
  replicas: {{ .Values.udm.replicaCount }}
  template:
    metadata:
      labels:
        project: {{ .Values.global.projectName }}
        nf: {{ .Values.udm.name }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/udm/udm-configmap.yaml") . | sha256sum }}-{{ include (print $.Template.BasePath "/global/free5gc-configmap.yaml") . | sha256sum }}
    spec:
      initContainers:
      - name: wait-nrf
        image: {{ .Values.initcontainers.curl.registry }}/{{ .Values.initcontainers.curl.image }}:{{ .Values.initcontainers.curl.tag }}
        env:
        - name: DEPENDENCIES
          value: {{ .Values.global.sbi.scheme }}://{{ .Values.nrf.service.name }}:{{ .Values.nrf.port }}
        command: ['sh', '-c', 'set -x; for dependency in $DEPENDENCIES; do while [ $(curl --connect-timeout 5 -s -o /dev/null -w "%{http_code}" $dependency) -ne 200 ]; do echo waiting for dependencies; sleep 1; done; done;']
      containers:
      - image: {{ .Values.global.image.registry }}/{{ .Values.udm.image.name }}:{{ .Values.udm.image.tag }}
        name: {{ .Values.udm.name }}
        ports:
        - containerPort: {{ .Values.udm.port }}
        command: ["./udm"]
        args: ["-udmcfg", "../config/udmcfg.yaml"]   
        env:
          - name: GIN_MODE
            value: release
        volumeMounts:
        - mountPath: {{ .Values.volume.mount }}
          name: {{ .Values.udm.volume.name }}
        resources:
          requests:
            memory: "64Mi"
            cpu: "150m"
          limits:
            memory: "64Mi"
            cpu: "150m"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
      - name: {{ .Values.udm.volume.name }}
        projected:
          sources:
          - configMap:
              name: {{ .Values.udm.configmap.name }}
          - configMap:
              name: {{ .Values.free5gc.configmap.name }}
{{- end }}

