#
# Software Name : towards5gs-helm
# SPDX-FileCopyrightText: Copyright (c) 2021 Orange
# SPDX-License-Identifier: Apache-2.0
#
# This software is distributed under the Apache License 2.0,
# the text of which is available at todo
# or see the "LICENSE" file for more details.
#
# Author: Abderaouf KHICHANE, Ilhem FAJJARI, Ayoub BOUSSELMI
# Software description: An open-source project providing Helm charts to deploy 5G components (Core + RAN) on top of Kubernetes
#
{{- if .Values.webui.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.webui.service.name }}
  labels:
    project: {{ .Values.global.projectName }}
    app: {{ .Values.webui.name }}
spec:
  type: {{ .Values.webui.service.type }}
  ports:
    - port: {{ .Values.webui.port }}
      nodePort: {{ .Values.webui.service.nodePort }}
  selector:
    project: {{ .Values.global.projectName }}
    app: {{ .Values.webui.name }}
{{- end }}
