#
# Software Name : towards5gs-helm
# SPDX-FileCopyrightText: Copyright (c) 2021 Orange
# SPDX-License-Identifier: Apache-2.0
#
# This software is distributed under the Apache License 2.0,
# the text of which is available at todo
# or see the "LICENSE" file for more details.
#
# Author: Abderaouf KHICHANE, Ilhem FAJJARI, Ayoub BOUSSELMI
# Software description: An open-source project providing Helm charts to deploy 5G components (Core + RAN) on top of Kubernetes
#
# Default values for ueransim-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  userPlaneArchitecture: oneupf  # possible values are "oneupf" and "ulcl"
  multiCluster: false
  cpClusterIP: 192.168.121.16
  uesubnet: 10.1.0.0/16
  datanetworks:
    dn1: &dn1 internet
    dn2: internet2
  image:
    registry: towards5gs
  upf:
    n4if:  # PFCP
      ipAddress: 10.100.50.241
    n3if:  # GTPU
      ipAddress: 10.100.50.233
    n6if:  # DN
      ipAddress: 10.100.100.12
  upfb:
    n4if:  # PFCP
      ipAddress: 10.100.50.241
    n3if:  # GTPU
      ipAddress: 10.100.50.233
    n6if:  # DN
      ipAddress: 10.100.100.12
  upf1:
    n4if:  # PFCP
      ipAddress: 10.100.50.242
    n3if:  # GTPU
      ipAddress: 10.100.50.234
    n6if:  # DN
      ipAddress: 10.100.100.13
  upf2:
    n4if:  # PFCP
      ipAddress: 10.100.50.243
    n3if:  # GTPU
      ipAddress: 10.100.50.235
    n6if:  # DN
      ipAddress: 10.100.100.14
  amf:
    n2if:  # NGAP
      ipAddress: 10.100.50.249
    service:
      ngap:
        enabled: false
        name: amf-n2
        port: 38412
        nodeport: 31412
        protocol: SCTP
        type: NodePort
  gnb:
    n3if:
      ipAddress: 10.100.50.236

projectName: ueransim

gnb:
  enabled: true
  name: gnb
  replicaCount: 1
  image:
    name: ueransim-gnb
    tag: "v3.1.3"
  configmap:
    name: gnb-configmap
  volume:
    name: gnb-volume
    mount: /ueransim/config
  service:
    name: gnb-service
    type: ClusterIP
    port: 4997
    protocol: UDP
  configuration:
    mcc: '208' # Mobile Country Code value
    mnc: '93'  # Mobile Network Code value (2 or 3 digits)
    nci: '0x000000010'  # NR Cell Identity (36-bit)
    idLength: 32        # NR gNB ID length in bits [22...32]
    tac: 1     # Tracking Area Code
    # List of supported S-NSSAIs by this gNB
    slices:
      - sst: 0x1
        sd: 0x010203
    # Indicates whether or not SCTP stream number errors should be ignored.
    ignoreStreamIds: true
ue:
  enabled: true
  name: ue
  replicaCount: 1
  image:
    name: ueransim-ue
    tag: "v3.1.3"
  configmap:
    name: ue-configmap
  volume:
    name: ue-volume
    mount: /ueransim/config
  command: "./nr-ue -c ../config/ue-config.yaml"  # This is the command that will be launched in the UE container
  # A script that will be run after the UE creation. It may be used to periodically generate traffic
  script: ""
  configuration: 
    supi: "imsi-208930000000003"  # IMSI number
    mcc: '208' # Mobile Country Code value
    mnc: '93' # Mobile Network Code value (2 or 3 digits)
    key: "8baf473f2f8fd09487cccbd7097c6862" # Operator code (OP or OPC) of the UE
    op: "8e27b6af0e692e750f32667a3b14605d" # This value specifies the OP type and it can be either 'OP' or 'OPC'
    opType: "OPC" # This value specifies the OP type and it can be either 'OP' or 'OPC'
    amf: '8000' # Authentication Management Field (AMF) value
    imei: '356938035643803' # IMEI number of the device
    imeiSv: '4370816125816151'
    sessions:
      - type: "IPv4"
        apn: "internet"
        slice:
          sst: 0x01
          sd: 0x010203
    # Configured NSSAI for this UE by HPLMN
    configured-nssai:
      - sst: 0x01
        sd: 0x010203
    # Default Configured NSSAI for this UE
    default-nssai:
      - sst: 1
        sd: 1
    # Supported encryption and integrity algorithms by this UE
    integrity:
      IA1: true
      IA2: true
      IA3: true
    ciphering:
      EA1: true
      EA2: true
      EA3: true

ue1:
  configuration: 
    supi: "imsi-208930000000003"  # IMSI number
    mcc: '208' # Mobile Country Code value
    mnc: '93' # Mobile Network Code value (2 or 3 digits)
    key: "8baf473f2f8fd09487cccbd7097c6862" # Operator code (OP or OPC) of the UE
    op: "8e27b6af0e692e750f32667a3b14605d" # This value specifies the OP type and it can be either 'OP' or 'OPC'
    opType: "OPC" # This value specifies the OP type and it can be either 'OP' or 'OPC'
    amf: '8000' # Authentication Management Field (AMF) value
    imei: '356938035643803' # IMEI number of the device
    imeiSv: '4370816125816151'
    sessions:
      - type: "IPv4"
        apn: "internet"
        slice:
          sst: 0x01
          sd: 0x010203
    # Configured NSSAI for this UE by HPLMN
    configured-nssai:
      - sst: 0x01
        sd: 0x010203
    # Default Configured NSSAI for this UE
    default-nssai:
      - sst: 1
        sd: 0x010203
    # Supported encryption and integrity algorithms by this UE
    integrity:
      IA1: true
      IA2: true
      IA3: true
    ciphering:
      EA1: true
      EA2: true
      EA3: true

ue2:
  configuration: 
    supi: "imsi-208930000000003"  # IMSI number
    mcc: '208' # Mobile Country Code value
    mnc: '93' # Mobile Network Code value (2 or 3 digits)
    key: "8baf473f2f8fd09487cccbd7097c6862" # Operator code (OP or OPC) of the UE
    op: "8e27b6af0e692e750f32667a3b14605d" # This value specifies the OP type and it can be either 'OP' or 'OPC'
    opType: "OPC" # This value specifies the OP type and it can be either 'OP' or 'OPC'
    amf: '8000' # Authentication Management Field (AMF) value
    imei: '356938035643803' # IMEI number of the device
    imeiSv: '4370816125816151'
    sessions:
      - type: "IPv4"
        apn: "internet2"
        slice:
          sst: 0x01
          sd: 0x112233
    # Configured NSSAI for this UE by HPLMN
    configured-nssai:
      - sst: 0x01
        sd: 0x112233
    # Default Configured NSSAI for this UE
    default-nssai:
      - sst: 1
        sd: 0x112233
    # Supported encryption and integrity algorithms by this UE
    integrity:
      IA1: true
      IA2: true
      IA3: true
    ciphering:
      EA1: true
      EA2: true
      EA3: true


n2if:  # NGAP
  ipAddress: 10.100.50.250

datanetwork: *dn1

createNetworks: true

networks5g:
  n4network:
    enabled: false
    name: n4network
    subnetIP: 10.100.50.240
  n3network:
    enabled: false
    name: n3network
    subnetIP: 10.100.50.232
    cidr: 29
  n6network:
    enabled: false
    name: n6network
    subnetIP: 10.100.100.0     # The prefix IP of the Data Network
    gateway: 1
  n2network:
    name: n2network
    subnetIP: 10.100.50.248
    cidr: 29
  n9network:
    enabled: false
  ovn4nfv:       # The ovn4nfv plugin can be used for N3 and N6 interfaces
    enabled: false
    name: ovn4nfv-k8s-plugin
    n6network:
      name: n6net
    n3network:
      name: n3net
