#
# Software Name : towards5gs-helm
# SPDX-FileCopyrightText: Copyright (c) 2021 Orange
# SPDX-License-Identifier: Apache-2.0
#
# This software is distributed under the Apache License 2.0,
# the text of which is available at todo
# or see the "LICENSE" file for more details.
#
# Author: Abderaouf KHICHANE, Ilhem FAJJARI, Ayoub BOUSSELMI
# Software description: An open-source project providing Helm charts to deploy 5G components (Core + RAN) on top of Kubernetes
#
{{- if .Values.gnb.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.gnb.configmap.name }}
  labels:
    app: {{ .Values.projectName }}
    component: {{ .Values.gnb.name }}
data:
  gnb-config.yaml: |

{{- toYaml .Values.gnb.configuration | nindent 4 }}
    
    linkIp: 0.0.0.0   # gNB's local IP address for Radio Link Simulation (Usually same with local IP)
    # gNB's local IP address for N2 Interface (Usually same with local IP)
{{- if .Values.global.amf.service.ngap.enabled }}
    ngapIp: 0.0.0.0   
{{- else }}
    ngapIp: {{ .Values.n2if.ipAddress }} 
{{- end }}
    gtpIp: {{ .Values.global.gnb.n3if.ipAddress }}    # gNB's local IP address for N3 Interface (Usually same with local IP)
    
    # List of AMF address information
    amfConfigs:
{{- if .Values.global.amf.service.ngap.enabled }}
{{- if .Values.global.multiCluster }}
      - address: {{ .Values.global.cpClusterIP }}
        port: {{ .Values.global.amf.service.ngap.nodeport }}
{{- else }}
      - address: {{ .Values.global.amf.service.ngap.name }}
        port: {{ .Values.global.amf.service.ngap.port }}
{{- end }}
{{- else }}
      - address: {{ .Values.global.amf.n2if.ipAddress }}
        port: {{ .Values.global.amf.service.ngap.port }}
{{- end }}

{{- end }}
