#
# Software Name : towards5gs-helm
# SPDX-FileCopyrightText: Copyright (c) 2021 Orange
# SPDX-License-Identifier: Apache-2.0
#
# This software is distributed under the Apache License 2.0,
# the text of which is available at todo
# or see the "LICENSE" file for more details.
#
# Author: Abderaouf KHICHANE, Ilhem FAJJARI, Ayoub BOUSSELMI
# Software description: An open-source project providing Helm charts to deploy 5G components (Core + RAN) on top of Kubernetes
#
{{- if eq .Values.global.userPlaneArchitecture "ulcl" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Values.upfb.name }}
  labels:
    project: {{ .Values.global.projectName }}
    nf: {{ .Values.upfb.name }}
spec:
  selector:
    matchLabels:
      project: {{ .Values.global.projectName }}
      nf: {{ .Values.upfb.name }}
  replicas: {{ .Values.upfb.replicaCount }}
  template:
    metadata:
      labels:
        project: {{ .Values.global.projectName }}
        nf: {{ .Values.upfb.name }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/upfb/upfb-configmap.yaml") . | sha256sum }}
{{- if or (not .Values.global.ovn4nfv.enabled) (not .Values.global.upf.service.pfcp.enabled) }}
        k8s.v1.cni.cncf.io/networks: '[
{{- if not .Values.global.ovn4nfv.enabled }}
          { "name": "{{ .Values.global.n9network.name }}", "interface": "n9", "ips": [ "{{ .Values.global.upfb.n9if.ipAddress }}/{{ .Values.global.n9network.cidr }}" ] },
          { "name": "{{ .Values.global.n3network.name }}", "interface": "n3", "ips": [ "{{ .Values.global.upfb.n3if.ipAddress }}/{{ .Values.global.n3network.cidr }}" ] },
          { "name": "{{ .Values.global.n6network.name }}", "interface": "n6", "ips": [ "{{ .Values.global.upfb.n6if.ipAddress }}/{{ .Values.global.n6network.cidr }}" ] }{{- end }}{{- if and (not .Values.global.upf.service.pfcp.enabled) (not .Values.global.ovn4nfv.enabled) }},{{- end }}
{{- if not .Values.global.upf.service.pfcp.enabled }}
          { "name": "{{ .Values.global.n4network.name }}", "interface": "n4", "ips": [ "{{ .Values.global.upfb.n4if.ipAddress }}/{{ .Values.global.n4network.cidr }}" ] }
{{- end }}
          ]'
{{- end }}
{{- if .Values.global.ovn4nfv.enabled }}
        k8s.v1.cni.cncf.io/networks: {{ .Values.global.ovn4nfv.name }}
        k8s.plugin.opnfv.org/nfn-network: '{ "type": "ovn4nfv", "interface": [{ "name": "{{ .Values.global.ovn4nfv.n6network.name }}", "ipAddress":"{{ .Values.global.upfb.n6if.ipAddress }}", "interface": "n6" , "defaultGateway": "false"}, { "name": "{{ .Values.global.ovn4nfv.n3network.name }}", "ipAddress": "{{ .Values.global.upfb.n3if.ipAddress }}", "interface": "n3" , "defaultGateway": "false"}, { "name": "{{ .Values.global.ovn4nfv.n9network.name }}", "ipAddress": "{{ .Values.global.upfb.n9if.ipAddress }}", "interface": "n9" , "defaultGateway": "false"}]}'
{{- end }}
    spec:
      containers:
      - image: {{ .Values.global.image.registry }}/{{ .Values.upf.image.name }}:{{ .Values.upf.image.tag }}
        name: {{ .Values.upfb.name }}
        ports:
        - name: n4
          containerPort: {{ .Values.global.upf.service.pfcp.port }}
          protocol: {{ .Values.global.upf.service.pfcp.protocol }}
        securityContext:
          capabilities:
            add: ["NET_ADMIN"]
        command: ["/free5gc/config/wrapper.sh"]
        volumeMounts:
        - mountPath: {{ .Values.upf.volume.mount }}
          name: {{ .Values.upfb.volume.name }}
        resources:
          requests:
            memory: "256Mi"
            cpu: "1"
          limits:
            memory: "256Mi"
            cpu: "1"
      restartPolicy: Always
      volumes:
      - name: {{ .Values.upfb.volume.name }}
        configMap:
          name: {{ .Values.upfb.configmap.name }}
          items:
          - key: upfcfgb.yaml
            path: upfcfg.yaml
          - key: wrapper.sh
            path: wrapper.sh
            mode: 0777
{{- end }}

