#
# Software Name : towards5gs-helm
# SPDX-FileCopyrightText: Copyright (c) 2021 Orange
# SPDX-License-Identifier: Apache-2.0
#
# This software is distributed under the Apache License 2.0,
# the text of which is available at todo
# or see the "LICENSE" file for more details.
#
# Author: Abderaouf KHICHANE, Ilhem FAJJARI, Ayoub BOUSSELMI
# Software description: An open-source project providing Helm charts to deploy 5G components (Core + RAN) on top of Kubernetes
#
{{- if eq .Values.global.userPlaneArchitecture "ulcl" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.upfb.configmap.name }}
  labels:
    app: {{ .Values.global.projectName }}
data:
  upfcfgb.yaml: |
    info:
      version: 1.0.0
      description: UPF configuration
    
    configuration:
      # debugLevel: panic|fatal|error|warn|info|debug|trace
      debugLevel: info
      ReportCaller: false
    
      pfcp:
{{- if not .Values.global.upf.service.pfcp.enabled }}
        - addr: {{ .Values.global.upfb.n4if.ipAddress }}
{{- else }}
        - addr: 0.0.0.0
{{- end }}
    
      gtpu:
        - addr: {{ .Values.global.upfb.n3if.ipAddress }}
        - addr: {{ .Values.global.upfb.n9if.ipAddress }}
        # [optional] gtpu.name
        # - name: upf.5gc.nctu.me
        # [optional] gtpu.ifname
        # - ifname: gtpif
    
      dnn_list:
        - dnn: {{ .Values.global.datanetworks.dn1 }}
          cidr: {{ .Values.global.uesubnet1 }}
          # [optional] apn_list[*].natifname
        #  natifname: n6

  wrapper.sh: |
    #!/bin/bash

    iptables -A FORWARD -j ACCEPT
    iptables -t nat -A POSTROUTING -s {{ .Values.global.uesubnet }} -o n6 -j MASQUERADE  # Allow routing traffic comming from the UE SUBNET to the interface N6
    iptables -t nat -A POSTROUTING -o n9 -j MASQUERADE
    iptables -t nat -A POSTROUTING -o n3 -j MASQUERADE

    /free5gc/free5gc-upfd/free5gc-upfd -f /free5gc/config/upfcfg.yaml

{{- end }}

